spring.application.name=apipedidos

# Base de datos PostgreSQL en Render
spring.datasource.url=jdbc:postgresql://dpg-d7jievd7vvec7398ncm0-a.oregon-postgres.render.com/pedidos_3wyt
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=pedidos_3wyt_user
spring.datasource.password=mJKhS3sLrTVBsZU69h75rBuWBRe6sIRS

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 local (descomentar para desarrollo sin internet)
#spring.datasource.url=jdbc:h2:mem:apipedidos
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.h2.console.enabled=true
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=create-drop
