spring.application.name=apipedidos

# Base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d6u7dq14tr6s73el79l0-a.oregon-postgres.render.com/pedidos_ab6l
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=pedidos_ab6l_user
spring.datasource.password=3ebGi8ZKjgodA9X4fVNOyVq28d3EpeBD

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
